version: "3"
services:
  db:
    image: postgres
    container_name: mewa-rag-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: mewarag
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: mewarag-redis
    ports:
      - 6379:6379
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: mewa-qdrant
    ports:
      - 6333:6333
    volumes:
      - ./volumes/qdrant:/qdrant/storage
    restart: always
